version: '3'

services:
  mysql:
    restart: always
    privileged: true
    image: mysql:8.0
    container_name: mysql
    volumes:
      - ./conf:/etc/mysql/conf.d
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
    environment:
      MYSQL_ROOT_PASSWORD: "Abc114514"
      MYSQL_INITDB_SKIP_TZINFO: "Asia/Shanghai"
      MYSQL_DATABASE: "TodoList"
    ports:
      - 33106:3306
    networks:
      - todo_net

  #redis容器 - Redis container
  redis:
    image: redis:6.2.5
    container_name: redis
    ports:
      - 36379:6379
    environment:
      TZ: Asia/Shanghai
    command: "redis-server --requirepass 123456  --appendonly yes"
    privileged: true
    restart: always
    networks:
      - todo_net


networks:
  todo_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16